# text: menu item text
# url: link passed to browser. Specified relative so that testing can be done locally
# longurl: link calculated by browser, used for matching active page
markdown: rdiscount
pygments: true
navigation:
- text: Speakers
  url: speakers.html
  longurl: /speakers.html
- text: Workshops
  url: workshops.html
  longurl: /workshops.html
- text: Venue
  url: venue.html
  longurl: /venue.html
- text: Sponsors
  url: sponsors.html
  longurl: /sponsors.html
- text: Contact
  url: contact.html
  longurl: /contact.html
2012navigation:
- text: 
  url: /2012/
- url: /2012/details
  text: Details
- url: /2012/speakers
  text: Speakers
- url: /2012/schedule
  text: Schedule
- url: /2012/sponsors
  text: Sponsors
- url: /2012/location
  text: Location
- url: /2012/feedback-form
  text: Feedback
