markdown: rdiscount
pygments: true
navigation:
- text: 
  longurl: 
  url: 
- text: Speakers
  url: /tell-a-story
- text: Sponsors
  url: /sponsor-packages
2012navigation:
- text: 
  url: /2012/
- url: /2012/details
  text: Details
- url: /2012/speakers
  text: Speakers
- url: /2012/schedule
  text: Schedule
- url: /2012/sponsors
  text: Sponsors
- url: /2012/location
  text: Location
- url: /2012/feedback-form
  text: Feedback
