markdown: rdiscount
pygments: true
navigation:
- text: Speakers
  url: /speakers
- text: Workshops
  url: /workshops
- text: Venue
  url: /venue
- text: Sponsors
  url: /sponsors
- text: Contact
  url: /contact
2012navigation:
- text: 
  url: /2012/
- url: /2012/details
  text: Details
- url: /2012/speakers
  text: Speakers
- url: /2012/schedule
  text: Schedule
- url: /2012/sponsors
  text: Sponsors
- url: /2012/location
  text: Location
- url: /2012/feedback-form
  text: Feedback
speakers:
- name: Daniel
  surname: Fiske
  company: Rightshift
- name: Daniel
  surname: Schauenberg
  title: CEO and Founder
  company: Etsy
  title: Software Engineer
- name: Mike
  surname: Jones
  company: Western Cape Labs
  title: Jack of all trades
- name: Miles
  surname: Ward
  company: Amazon
  title: Evangelist
- name: David
  surname: Tinker
  company: Brandseye
  title: Title
- name: Neil
  surname: Blakey-Milner
  company: Facebook
  title: Production Engineer
- name: RI
  surname: Pienaar
  company: PuppetLabs
  title: Developer
- name: Robert
  surname: Stuttaford
  company: Cognician
- name: Dave
  surname: Humby
  company: Nomanini
  title: CTO
- name: Kenny
  surname: Gryp
  company: Percona
