markdown: rdiscount
highlighter: pygments
navigation:
- text: Home
  url: /
- text: Speakers
  url: /speakers
- text: Schedule
  url: /schedule
- text: Workshops
  url: /workshops
- text: Tickets
  url: /purchase
- text: Venue
  url: /venue
- text: Sponsors
  url: /sponsors
- text: About
  url: /about
- text: Videos
  url: /videos
year: 2015
