navigation:
- text: Home
  url: /
- text: Speakers
  url: /speakers
- text: Schedule
  url: /schedule
- text: Tickets
  url: /purchase
- text: Venue
  url: /venue
- text: Sponsors
  url: /sponsors
- text: About
  url: /about
- text: Videos
  url: /videos
- text: Contact
  url: /contact
year: 2016
