markdown: rdiscount
highlighter: pygments
navigation:
- text: Home
  url: /
- text: Speakers
  url: /speakers
- text: Schedule
  url: /schedule
- text: Workshops
  url: /workshops
- text: Tickets
  url: /purchase
- text: Venue
  url: /venue
- text: Sponsors
  url: /sponsors
- text: About
  url: /about
- text: Videos
  url: /videos



all_speakers_archive: [ beat_schwegler, dale_humby, daniel_fiske, daniel_schauenberg, david_tinker, mike_jones, miles_ward, neil_blakey_milner, patrick_turley, peter_lockhart, robert_stuttaford, simon_ratcliffe ]
all_speakers: [ niklas_gustavsson, aslam_khan, chris_bray, deon_moolman, clinton_gormley, beat_schwegler_2014, krzysztof_debski, shai_rosenfeld, dustin_whittle, zabil_cheriya_maliackal, simbarashe_nyatsa, simon_cross, wim_godden, ben_adlard, craig_robinson ]
speakers_1: [ niklas_gustavsson, aslam_khan, krzysztof_debski ]
speakers_2: [ chris_bray, deon_moolman, shai_rosenfeld ]
speakers_3: [ clinton_gormley, beat_schwegler_2014, dustin_whittle ]
speakers_4: [ zabil_cheriya_maliackal, simbarashe_nyatsa, simon_cross ]
speakers_5: [ wim_godden, ben_adlard, craig_robinson ]
highlighted: [ niklas_gustavsson, deon_moolman, clinton_gormley, chris_bray ]
nonhighlighted: [ aslam_khan, beat_schwegler_2014 ]
sponsors:
  praekelt:
    website_text: >
      Praekelt Foundation builds open source, scalable mobile technologies and solutions to improve the health and wellbeing of people living in poverty. Our programmes have reached over 50 million people across 15 countries in sub-Saharan Africa
  '2go':
    website_text: >
      2go is a mobile messenger that allows you to communicate for free with your
      friends. It is a network of millions of people where you can setup your
      profile, meet new people, talk to friends, share files and pictures!
      </p>
      <p>
      2go allows you to communicate with your friends for free. 2go does require a
      network connection which your mobile operator charges you a small amount
      for, but this costs much less than it would cost to send an SMS.
      </p>
      <p>
      With your mobile phone, visit <a href='http://wap.2go.im'>wap.2go.im</a>
      where you will need to fill in a very simple registration form. Your phone
      will then download the 2go application and you can begin chatting!
  amazon:
    website_text: >
      Amazon has a thriving technical centre in Cape Town! This is the centre
      where <a href='http://ec2.amazonaws.com/'>Amazon Elastic Compute Cloud
      (Amazon EC2)</a> was first created in 2005. In 2006 the Cape Town team
      launched <a href='http://ec2.amazonaws.com/'>Amazon EC2</a>. In 2012,
      Amazon started building an <a href='http://aws.amazon.com/premiumsupport/'>
      AWS Support</a> group based in Cape Town.
      </p>
      <p>
      In addition, our Kumo Development team owns the services and user
      interfaces required to deliver various AWS Support features to our
      customers. The team builds applications that encompass a variety of
      technical areas such as Information Retrieval, Data Mining, and building
      scalable systems that close the last mile gap with AWS Customers like
      Netflix. An example application is
      <a href='https://aws.amazon.com/premiumsupport/trustedadvisor/'>AWS Trusted
      Advisor</a> which performs data mining for customers and gives precise
      recommendation on cost optimization, security, fault tolerance and
      performance. In this team you will work across all AWS Customers from big &
      diverse enterprises to small customers as they move their infrastructure to
      the cloud. You will get firsthand experience interacting across all AWS
      services such as EC2, RDS, S3, Redshift, DynamoDB and others. Being an
      innovative solution in the industry, first of its kind for cloud computing,
      complex AWS Services and immense amounts of data makes our problems very
      challenging.
      </p>
      <p>
      The Cape Town <a href='http://aws.amazon.com/premiumsupport/'>AWS
      Support</a> team provides global technical support to external customers,
      helping them build mission-critical applications using AWS services such as
      EC2, S3 and RDS.
      </p>
      <p>
      The Amazon Development Centre in Cape Town, South Africa is seeking a
      number of talented software engineers, system engineers, technical managers
      and team leads who can work in an environment that is technically
      demanding, agile and believes in delivering high quality products to our
      customers. You will be surrounded by people that are wickedly smart and
      passionate about cloud computing..  If you are interested in any of these
      vacancies, please go to the <a
      href='http://www.adccpt.co.za/?page_id=19'>Job opportunities</a> page.
  elasticsearch:
    website_text: >
      Elasticsearch is on a mission to make massive amounts of data usable for
      businesses everywhere by delivering the world’s most advanced search and
      analytics engine available. With a laser focus on achieving the best user
      experience imaginable, the Elasticsearch ELK stack - comprised of
      Elasticsearch, Logstash, and Kibana - has become one of the most popular
      and rapidly growing open source solutions in the market. To learn more,
      visit <a href='http://elasticsearch.com'>elasticsearch.com</a>.
  facebook:
    website_text: >
      Founded in 2004, Facebook’s mission is to make the world more open and
      connected. People use Facebook to stay connected with friends and family, to
      discover what’s going on in the world, and to share and express what matters
      to them.
      </p>
      <p>
      Connecting everyone, understanding the world, and building the knowledge
      economy are huge technical challenges. Engineers at Facebook move fast and
      push code everyday to build infrastructure and products that provide global,
      real-time, and interconnected services for the 1.2 billion people who visit
      Facebook every month.
  google:
    website_text: >
      Google’s innovative search technologies connect millions of people around
      the world with information every day. Founded in 1998 by Stanford Ph.D.
      students Larry Page and Sergey Brin, Google today is a top web property in
      all major global markets. Google's mission in Africa is to make the internet
      an integral part of everyday life in Africa, by increasing its relevance and
      usefulness, eliminating access barriers for potential users, and developing
      products that are meaningful for the countries in the region. Google is
      headquartered in Silicon Valley with offices throughout the Americas,
      Europe, Africa and Asia.
      </p>
      <p>
      For more information, visit <a href='http://developers.google.com'>
      developers.google.com</a>, and follow us on
      <a href='https://plus.google.com/+GoogleDevelopers'>Google+</a>
  hetzner:
    website_text: >
      At Hetzner South Africa we are passionate about web hosting – it’s our
      core business and it’s what we do best. By consistently delivering
      excellent service and cost effective web hosting, dedicated servers and
      custom hosting solutions, Hetzner has exponentially grown its market
      share, making it the leading web hosting company in South Africa.
      </p>
      <p>
      Inspired by our brand promise ‘Trusted in Hosting’, we focus on providing
      efficient, sustainable business models, quality service and customer
      satisfaction. A key contributor to our success is our people. We aim for
      our teams to manage themselves rather than rely on several layers of
      hierarchy. We want to give our people the freedom to explore, innovate and
      create. We recognise that our customers expect reliability and good value
      from us and it remains our ongoing commitment to earn and retain their
      trust.
  key_connections:
    website_text: >
      Key Connections is  a technology recruitment company that specialises in
      placing developers throughout South Africa. We’re not like other “tech
      recruiters” who don’t know the difference between "Java" and "JavaScript"!
      </p>
      <p>
      We work with technology focused companies that treat their developers well, and
      build cool stuff. We have placed developers in starts ups, SME's and some of the
      world's largest tech companies.
      </p>
      <p>
      If you’re looking to recruit a team of developers we’d love to hear from you.
      </p>
      <p>
      We have clients looking for developers across all major programming languages.
      <a href='http://jobs.keyconnections.co.za/keyconnections/Search/Results/All/1'>Check out some of our recent jobs.</a>
      </p>
  mxit:
    website_text: >
      <b>About Mxit</b>
      Mxit is South Africa’s home-grown mobile social network. At Mxit, we know that
      conversation is at  the heart of everything. When people share rich
      conversations, they move forward – it’s how we  connect, discover and grow.
      <p>
      <b>Key features include:</b>
      </p>
      <p><i>Super Chat</i></p>
      <p>
      Mxit works on almost any phone and tablet, and is tailored to each device. This
      way, you can  enjoy the richest chat and networking experience possible. Enhance
      your profile with large cover  pictures, update your status and keep track of
      your friends in Newsfeed, create multiple profiles  and easily switch between
      them, and use our cool Backdrop feature to take pictures from your  Photo Stream
      and drop them into a shared chat background.
      </p>
      <p><i>Group Chat</i></p>
      <p>
      </p>
      Our new, more powerful Group Chat lets you speak to up to 50 people at once.
      Your friends can  easily invite their friends to the chat too, introducing you
      to more new people across almost every  type of phone. You can easily share
      photos and sound clips, and with our Chat Tabs, switching  between multiple
      conversations is so quick, you’ll never miss out.
      </p>
      <p><i>Chat Cards</i></p>
      <p>
      Super-charge your chat! Our unique Chat Cards allows you to grab web content,
      drop in videos,  share music tracks or mix up your chat with jokes and pickup
      lines to instantly spark new  conversations.
      </p>
  oracle:
    website_text: >
      Oracle Cloud Development Centre - Cape Town
      At the Oracle Cloud Development Centre in Cape Town, we build the
      core technology on which all Oracle’s cloud offerings are based,
      alongside our sister team in Santa Clara, Silicon Valley. Key focus
      areas include scale, performance and reliability. Oracle is committed
      to Cloud and we are growing an ace engineering team to accomplish our
      ambitious cloud goals. If you're interested in joining out team,
      please get in touch.
      </p>
      <p>
      Contact Syed Suhaib - syed.suhaib@oracle.com
  rackspace:
    website_text: >
  rsaweb:
    website_text: >
      Established in 2001, we have extensive industry experience. Our commitment
      to customer service excellence and our in depth technical understanding,
      allows us to retain partnerships with some of SA's leading brands from a
      wide array of sectors.
      </p>
      <p>
      We take pride in offering our clients the best in service and support, and
      our SLA's ensure all clients absolute peace-of-mind, with a 24-hour
      help-desk fully supporting and monitoring all services.
      </p>
      <p>
      We have invested heavily in our infrastructure and have a strong presence
      in South Africa and Internationally with data centres in Johannesburg and
      Cape Town, and POPs (points of presence) in London, Europe and the USA.
      </p>
      <p>
      We believe that great technology doesn't have to be complex and expensive;
      our motto 'technology meets life' implies just that. We bridge the gap
      between IT innovation and everyday life - and our team take pride in doing
      this every day.
  microsoft:
    website_text: >
      <b>
      Tech Startups - Avoid Sleepless Nights with Microsoft BizSpark
      </b>
      <p>
      At Microsoft we're big on business and being proudly South African. For decades
      we've focused on becoming a strategic partner to the growth of this country by
      championing sustainable development through technology. In the early days our
      goal was to put a computer on every desk. Today we aim to change the lives of
      millions by developing products and solutions that people love and businesses
      need.
      </p>
      <p>
      We firmly believe that access to education and opportunity is the foundation
      upon which great nations are built. That's why we have invested in South Africa
      by continually supporting its rapidly emerging SME sector. Individuals who are
      brave enough to nurture their own creative ideas into platforms for job creation
      and economic growth should be celebrated. They are the engines that keep our
      country's economy ticking.
      </p>
      <p>
      With this in mind, we'd like to introduce Microsoft BizSpark.
      </p>
      <p>
      It is important to recognise the role technology startups play as significant
      contributors to the small enterprise mix. In just a few years businesses of this
      nature have revolutionised the way the world works by introducing services and
      platforms that simply did not exist before.
      </p>
      <p>
      To help drive this message forward Microsoft South Africa has initiated the
      BizSpark programme, a supportive forum that aims to drive the founding and
      growth of up to 600 technology start ups over the next three years.
      </p>
      <p>
      With assistance from the Jobs Fund we are partnering with South Africa's most
      inspiring technology SMEs to help facilitate their growth and development. It's
      a 360° view that centres on you, the startup. BizSpark provides technology,
      support and a community that is focused on how you work, how you view the world
      and how you are getting out there to change it.
      </p>
      <p>
      BizSpark offers a comprehensive array of the latest products that are aimed at facilitating growth. Participation gives members the equivalent of an MSDN subscription at no cost. This includes get access to over 900 products such as Windows Azure, Visual Studio, Windows Server and Windows 8. Everything you need to succeed, without the price tag.
      The tools are just one aspect of the BizSpark approach. Members are also afforded access to Microsoft's Azure cloud platform - eradicating the restrictive costs often associated with hosting servers and purchasing storage capacity as a small business.
      It's a package designed with technology start-ups in mind. Licensing and hosting fees can be difficult to honour when you're starting out. Microsoft would like to give you the tools needed to build a business without the sleepless nights.
      Application to the Microsoft BizSpark programme is open to anyone, provided your business complies with certain expectations:
      </p>
      <p>
      <ul>
        <li>You must be actively engaged in development of a software- based product or service at the core of your current(or intended) business.  </li>
        <li>The software must add significant and primary functionality to the integrated Microsoft software. You need to own the software you're developing, i.e. you cannot be licensing it.  </li>
        <li>Your business must be privately held and have been in business for less than five years.  </li>
        <li>You need to be bringing in less than R5 million in annual revenue. </li>
      </ul>
      </p>
      <p>
      We know that it's tough out there, but we're with you every step of the way.
      </p>
      <p>
      To find out more visit the BizSpark Portal at <a href='http://www.bizsparksa.co.za'>www.bizsparksa.co.za</a>
      </p>
      <p>
      To learn more about Microsoft Azure visit our website - <a href='http://aka.ms/azuresa'>aka.ms/azuresa</a>
      </p>
      <p>

programme:
  - day: Wednesday Evening, 9th April
    schedule:
      - time: 5:00 pm - 9:30 pm
        event: Pre-conference drinks
        description: Come join us for pre-conference drinks at <a href="http://www.wembleytap.co.za/">the Wembley Tap</a> in Gardens, sponsored by <a href="http://scaleconf.org/sponsors/key_connections">Key Connections</a>. This will be a chance to socialise and network with the speakers, organisers, and fellow conference attendees
  - day: Thursday, 10th April
    schedule:
      - time: 8:00 am - 9:00 am
        event: Registration
        description: Tea and coffee will be served
      - time: 9:00 am - 9:15 am
        event: Opening
        description: A quick welcome and introduction to the conference before we get going
      - time: 9:30 am - 10:15 am
        speaker: niklas_gustavsson
      - time: 10:15 am - 10:25 am
        event: Break
        description: A quick changeover & pee-break
      - time: 10:25 am - 11:10 am
        speaker: wim_godden
      - time: 11:10 am - 11:30 am
        event: Break
        description: Mid-morning tea & coffee with scones and biscuits
      - time: 11:30 am - 12:15 pm
        speaker: beat_schwegler_2014
      - time: 12:15 pm - 1:30 pm
        event: Lunch
        description: A buffet lunch provided by Moyo and some time to chill in the Botanical Gardens
      - time: 1:30 pm - 2:15 pm
        speaker: krzysztof_debski
      - time: 2:15 pm - 2:30 pm
        event: Break
        description: Afternoon tea & coffee with biscuits
      - time: 2:30 pm - 3:15 pm
        speaker: simon_and_ben
      - time: 3:15 pm - 3:35 pm
        event: Break
        description: A quick changeover & pee-break
      - time: 3:35 pm - 4:20 pm
        speaker: clinton_gormley
      - time: 4:20 pm - 5:05 pm
        speaker: craig_robinson
  - day: Thursday evening, 10th April
    schedule:
      - time: 5:30 pm - 10:00 pm
        event: Party
        description: Join us at <a href="http://forries.co.za/">the Forrester's Arms</a> for food and drinks, sponsored by <a href="http://scaleconf.org/sponsors/amazon">Amazon Web Services</a>.
  - day: Friday, 11th April
    schedule:
      - time: 8:30 am - 9:00 am
        event: Arrival
        description: Tea and coffee will be served
      - time: 9:15 am - 10:00 am
        speaker: shai_rosenfeld
      - time: 10:00 am - 10:10 am
        event: Break
        description: A quick changeover & pee-break
      - time: 10:10 am - 10:55 am
        speaker: deon_moolman
      - time: 10:55 am - 11:25 am
        event: Break
        description: Mid-morning tea & coffee with scones and biscuits
      - time: 11:25 am - 12:10 pm
        speaker: chris_bray
      - time: 12:15 pm - 1:30 pm
        event: Lunch
        description: A buffet lunch provided by Moyo and some time to chill in the Botanical Gardens
      - time: 1:30 pm - 2:15 pm
        speaker: dustin_whittle
      - time: 2:15 pm - 2:35 pm
        event: Break
        description: A quick changeover & pee-break
      - time: 2:35 pm - 3:20 pm
        speaker: zabil_and_simba
      - time: 3:20 pm - 3:40 pm
        event: Break
        description: Afternoon tea & coffee with biscuits
      - time: 3:40 pm - 4:25 pm
        speaker: aslam_khan
      - time: 4:25 pm - 4:40 pm
        event: Closing
        description: Final remarks
  - day: Friday evening, 11th April
    schedule:
      - time: 5:00 pm - 11:00 pm
        event: Party
        description: >
            Join us at the post-conference party at <a href="http://riverclub.co.za/">Player's Restaurant, at the River Club</a> for food and drinks, sponsored by <a href="http://scaleconf.org/sponsors/facebook">Facebook</a>.
