navigation:
- text: Home
  url: /
- text: Speakers
  url: /speakers
- text: Schedule
  url: /schedule
- text: Tickets
  url: /purchase
- text: Venue
  url: /venue
- text: Sponsors
  url: /sponsors
- text: About
  url: /about
- text: Videos
  url: /videos
- text: Contact
  url: /contact
year: 2016
tickets_for_sale: false
waiting_list_enable: true
waiting_list_url: https://docs.google.com/forms/d/1WOB3UD0XMfljzwqoqvqIw36xnuDbPs0RcjZDG5_L_4o/viewform
