markdown: rdiscount
pygments: true
oldnavigation:
- text: 
  url: 
- url: /2012/details
  text: Details
- url: /2012/speakers
  text: Speakers
- url: /2012/schedule
  text: Schedule
- url: /2012/sponsors
  text: Sponsors
- url: /2012/location
  text: Location
- url: /2012/feedback-form
  text: Feedback
