conf_being_organised: false
tickets_for_sale: false
tickets_for_vip: false
tickets_for_public: false
quicket_productid: 13990
waiting_list_url: https://docs.google.com/forms/d/1WOB3UD0XMfljzwqoqvqIw36xnuDbPs0RcjZDG5_L_4o/viewform
dates: "TBC"
current_year: 2017
years:
  - 2017
  - 2016
  - 2015
  - 2014
  - 2013
